[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python3 -m http.server $PORT --bind 0.0.0.0"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
